name: Build & Deploy Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare site
        run: |
          MANIFEST_URL="https://guutches.github.io/comick-so-source/manifest.json"
          mkdir -p _site
          cp -r src _site/
          cp manifest.json _site/
          cat > _site/index.html <<EOF
          <!doctype html>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <title>ComicK (SO) — Paperback Repo</title>
          <style>
            body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Inter,Helvetica,Arial,sans-serif;margin:0;background:#0f172a;color:#e2e8f0;display:flex;min-height:100vh;align-items:center;justify-content:center}
            .card{background:#111827;padding:28px 28px 24px;border-radius:16px;box-shadow:0 10px 30px rgba(0,0,0,.35);max-width:640px;width:92%}
            h1{margin:0 0 12px;font-size:22px}
            p{margin:8px 0 16px;color:#cbd5e1}
            a.btn{display:inline-block;padding:12px 16px;border-radius:10px;background:#3b82f6;color:#fff;text-decoration:none;font-weight:600}
            code{background:#0b1220;color:#93c5fd;padding:2px 6px;border-radius:6px}
            .muted{color:#94a3b8;font-size:14px;margin-top:8px}
            .list{margin-top:18px}
          </style>
          <div class="card">
            <h1>ComicK (SO) — Paperback Source</h1>
            <p>Tap the button below on your iPhone/iPad with <b>Paperback</b> installed:</p>
            <p>
              <a class="btn" href="paperback://addRepo?url=https%3A%2F%2Fguutches.github.io%2Fcomick-so-source%2Fmanifest.json">Add to Paperback</a>
            </p>
            <div class="list">
              <p>Or add manually via <i>Paperback → Settings → External Sources → Add</i> using this URL:</p>
              <p><code>https://guutches.github.io/comick-so-source/manifest.json</code></p>
            </div>
            <p class="muted">If the deep link doesn’t open, copy the URL above and paste it in Paperback.</p>
          </div>
          EOF
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v4
